import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useNavigate, useLocation } from "react-router-dom";
import { TrendingUp, MessageSquare, Volume2, FileText } from "lucide-react";

const Feedback = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { transcript } = location.state || { transcript: [] };

  // Mock analysis - in production, this would be generated by AI
  const analysis = {
    clarity: 85,
    confidence: 78,
    contentDepth: 82,
    overallScore: 82,
    strengths: [
      "Clear articulation of technical concepts",
      "Good use of specific examples from experience",
      "Confident delivery in most responses"
    ],
    improvements: [
      "Could provide more quantitative results in project examples",
      "Consider structuring answers with STAR method",
      "Practice pausing before complex answers"
    ]
  };

  const ScoreCard = ({ title, score, icon: Icon }: { title: string; score: number; icon: any }) => (
    <Card className="p-6 shadow-elegant">
      <div className="flex items-center gap-3 mb-3">
        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
          <Icon className="w-5 h-5 text-primary" />
        </div>
        <h3 className="font-semibold">{title}</h3>
      </div>
      <div className="mb-2">
        <div className="flex justify-between text-sm mb-1">
          <span>Score</span>
          <span className="font-bold">{score}%</span>
        </div>
        <div className="h-2 bg-secondary rounded-full overflow-hidden">
          <div
            className="h-full gradient-primary transition-all duration-1000"
            style={{ width: `${score}%` }}
          />
        </div>
      </div>
    </Card>
  );

  return (
    <div className="min-h-screen gradient-hero py-12">
      <div className="container mx-auto px-4 max-w-5xl">
        <div className="text-center mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-3">Interview Feedback</h1>
          <p className="text-muted-foreground">
            Comprehensive analysis of your performance
          </p>
        </div>

        {/* Overall Score */}
        <Card className="p-8 mb-8 text-center shadow-elegant animate-fade-in [animation-delay:100ms]">
          <h2 className="text-2xl font-bold mb-2">Overall Performance</h2>
          <div className="text-6xl font-bold gradient-primary bg-clip-text text-transparent mb-2">
            {analysis.overallScore}%
          </div>
          <p className="text-muted-foreground">Great job! You're well-prepared for interviews.</p>
        </Card>

        {/* Score Breakdown */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="animate-fade-in [animation-delay:200ms]">
            <ScoreCard title="Clarity" score={analysis.clarity} icon={MessageSquare} />
          </div>
          <div className="animate-fade-in [animation-delay:300ms]">
            <ScoreCard title="Confidence" score={analysis.confidence} icon={Volume2} />
          </div>
          <div className="animate-fade-in [animation-delay:400ms]">
            <ScoreCard title="Content Depth" score={analysis.contentDepth} icon={FileText} />
          </div>
        </div>

        {/* Strengths & Improvements */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <Card className="p-6 shadow-elegant animate-fade-in [animation-delay:500ms]">
            <h3 className="font-semibold mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-success" />
              Key Strengths
            </h3>
            <ul className="space-y-2">
              {analysis.strengths.map((strength, idx) => (
                <li key={idx} className="text-sm flex items-start gap-2">
                  <span className="text-success mt-1">✓</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </Card>

          <Card className="p-6 shadow-elegant animate-fade-in [animation-delay:600ms]">
            <h3 className="font-semibold mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-accent" />
              Areas for Improvement
            </h3>
            <ul className="space-y-2">
              {analysis.improvements.map((improvement, idx) => (
                <li key={idx} className="text-sm flex items-start gap-2">
                  <span className="text-accent mt-1">→</span>
                  <span>{improvement}</span>
                </li>
              ))}
            </ul>
          </Card>
        </div>

        {/* Transcript Summary */}
        <Card className="p-6 shadow-elegant mb-8 animate-fade-in [animation-delay:700ms]">
          <h3 className="font-semibold mb-4">Interview Transcript</h3>
          <div className="max-h-64 overflow-y-auto space-y-3">
            {transcript.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-4">
                No transcript available
              </p>
            ) : (
              transcript.map((entry: any, idx: number) => (
                <div key={idx} className={`text-sm p-3 rounded-lg ${
                  entry.role === 'user' ? 'bg-primary/10' : 'bg-accent/10'
                }`}>
                  <span className="font-semibold text-xs uppercase text-muted-foreground">
                    {entry.role === 'user' ? 'You: ' : 'Interviewer: '}
                  </span>
                  {entry.text}
                </div>
              ))
            )}
          </div>
        </Card>

        {/* Actions */}
        <div className="flex gap-4 animate-fade-in [animation-delay:800ms]">
          <Button
            variant="outline"
            onClick={() => navigate("/")}
            className="flex-1"
          >
            Return Home
          </Button>
          <Button
            variant="hero"
            onClick={() => navigate("/job-analysis")}
            className="flex-1"
          >
            Start Another Interview
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Feedback;
